version: '3'
networks:
  micro-orm.net:
    driver: bridge
services:

  micro-orm.php:
    image: 'canals/php:8.2'
    ports:
      - '2080:80'
    volumes:
      - ../:/var/www
    working_dir: /var/www/
    networks:
      - micro-orm.net
    depends_on:
      - micro-orm.db

  micro-orm.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: .env
    ports:
      - '3307:3306'
    networks:
      - micro-orm.net

  adminer:
    image: adminer
    ports:
      - '8082:8080'
    networks:
      - micro-orm.net
